name: Deploy to GitHub Pages & InfinityFree FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.OMAH }}
          username: ${{ secrets.AKU }}
          password: ${{ secrets.KUNCI }}
          local-dir: ./build/
          server-dir: /htdocs/
          protocol: ftp
          port: ${{ secrets.PORT }}
          exclude: |
            **/.gitignore
            .git/
            .github/
            node_modules/
            package.json
            package-lock.json
            src/
            public/
            .git*
            !.nojekyll
